name: Yampl
inputs:
  file:
    description: Path to the file that should be patched.
    required: true
  values:
    description: List of values to replace in the provided file.
    required: true
  commit_message:
    description: If set, this action will invoke stefanzweifel/git-auto-commit-action with the given commit message.
    default: ""
runs:
  using: composite
  steps:
    - name: Install Yampl
      shell: bash
      run: brew install clevyr/tap/yampl
    - name: Patch file
      shell: bash
      run: yampl -i ${{ inputs.file }} -v ${{ inputs.values }}
    - name: Commit changes
      if: inputs.commit_message
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ inputs.commit_message }}
