name: Yampl
description: GitHub Action to invoke yampl during CI/CD.
inputs:
  file:
    description: Path to the file that should be patched.
    required: true
  values:
    description: List of values to replace in the provided file.
    required: true
  commit_message:
    description: If set, this action will invoke stefanzweifel/git-auto-commit-action with the given commit message.
    default: ""
  commit_branch:
    description: Git branch name, where changes should be pushed too. Required if Action is used on the `pull_request` event
    required: false
    default: ${{ github.head_ref }}
  yampl_version:
    description: Yampl version to install
    default: latest
runs:
  using: composite
  steps:
    - name: Install Yampl
      uses: clevyr/setup-yampl-action@v1
      with:
        version: ${{ inputs.yampl_version }}
    - name: Patch file
      shell: bash
      env:
        FILE: ${{ inputs.file }}
        VALUES: ${{ inputs.values }}
      run: |
        shopt -s globstar 2>/dev/null || true
        yampl --inplace --value="$VALUES" $FILE
    - name: Commit changes
      if: inputs.commit_message
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ inputs.commit_message }}
        branch: ${{ inputs.commit_branch }}
